apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: quarkus-podname
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-commit-id
    value: $(body.commits.id)