apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-podname-cicd
spec:
  description: >-
    The Pipline to buld and deploy the Quarkus Java App http://gogs.apps.cluster-ctos-3bad.ctos-3bad.example.opentlc.com/cytan/quarkus-podname.
  params:
    - name: APP_NAME
      type: string
      default: quarkus-podname
    - name: GIT_REPO
      type: string
      default: http://gogs.apps.cluster-b517.b517.sandbox1869.opentlc.com/cytan/quarkus-podname.git
    - name: GIT_REVISION
      type: string
      default: master
    - name: IMAGE_NAME
      type: string
      default: image-registry.openshift-image-registry.svc:5000/pipeline-tutorial/quarkus-podname
    - default: .
      name: PATH_CONTEXT
      type: string
    - name: NAMESPACE
      type: string
      default: pipeline-tutorial
    - name: GIT_COMMIT_ID
      type: string
      default: manual
  workspaces:
    - name: workspace 
    - name: maven-settings 
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: workspace
    - name: package
      taskRef:
        name: maven
        kind: ClusterTask
      runAfter:
        - fetch-repository
      params:
        - name: GOALS
          value: ['clean', 'package']
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: workspace
#    - name: unit-test
#      taskRef:
#        name: maven
#        kind: ClusterTask
#      runAfter:
#        - package
#      params:
#        - name: GOALS
#          value: ['test']
#      workspaces:
#        - name: maven-settings
#          workspace: maven-settings
#        - name: source
#          workspace: workspace
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
#        - unit-test
        - package
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME)'
        - name: TLSVERIFY
          value: 'false'
        - name: DOCKERFILE
          value: './src/main/docker/Dockerfile.jvm'
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      taskRef:
        name: deploy-app
        kind: Task
      runAfter:
        - build-image
      params:
        - name: DEPLOYMENT_NAME
          value: quarkus-podname
        - name: CURRENT_IMAGE
          value: '$(params.IMAGE_NAME)'
        - name: NEW_IMAGE_NAME
          value: '$(params.IMAGE_NAME)'
        - name: NEW_IMAGE_TAG
          value: "latest"
        - name: NEW_IMAGE_DIGEST
          value: $(tasks.build-image.results.IMAGE_DIGEST)
        - name: NAMESPACE
          value: '$(params.NAMESPACE)'
        - name: KUSTOMIZE_OVERLAY_DIR
          value: pipeline/app/base
        - name: GIT_COMMIT_ID
          value: '$(params.GIT_COMMIT_ID)'
      workspaces:
        - name: source
          workspace: workspace