apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-resource
spec:
  type: git
  params:
    - name: url
      value: 'http://gogs.apps.cluster-ctos-3bad.ctos-3bad.example.opentlc.com/cytan/quarkus-podname.git'
    - name: revision
      value: master